## Travis CI Configuration file

# Use barebones Travis image
language: c

# Only grab latest git commit (no need for history)
git:
  depth: 1

# Cache the compilers folder so we don't have to download and unpack it for every build
cache:
  directories:
    - $HOME/compilers/

# Download and unpack the latest GNU ARM Embedded Toolchain if it's not already there
#  Also add the gcc/bin folder to $PATH
install:
  - export GCC_DIR=$HOME/compilers/gcc-arm-none-eabi-8-2018-q4-major
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-gcc ]; then wget -nv $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME/compilers; fi
  - export PATH=$PATH:$GCC_DIR/bin

# List of tests to run ( `./build -w $BOARD $MAIN` )
env:
  - BOARD=uos3-proto MAIN=demo_blinky
  - BOARD=uos3-proto MAIN=demo_uart
  - BOARD=uos3-proto MAIN=demo_watchdog
  - BOARD=uos3-proto MAIN=tx-test
  - BOARD=uos3-proto MAIN=txrx-uart

# Command to run tests
script: ./build -w $BOARD $MAIN

# Additional jobs for Tests, and Doxygen documentation (only on master branch)
jobs:
  include:
    - stage: Module Tests
      env: 
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - lcov
      script: ./test -w
    - stage: Docs & Reports
      if: branch = master
      cache: skip
      install: skip
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - gcc-7
            - lcov
      env: 
      script: tools/travis_docs.sh
