name: OBC-Firmware

# Run the action on pushes/pull requests to GDP202021
on: 
  push:
    branches:
      - GDP202021
  
  pull_request:
    branches:
      - GDP202021

jobs:
  build:
    name: Build and Test All Modules
    runs-on: ubuntu-latest
    container: duncanrhamill/obc-fw-ubuntu

    steps:
      - uses: actions/checkout@v2
        with:
          path: obc-firmware
          
      # Run build script
      - name: Build (linux, debug, test)
        run: |
          cd obc-firmware
          chmod +x ./build
          ./build -t linux --test

      # Run all modules test
      - name: Run all modules test
        run: |
          cd obc-firmware
          ./builds/debug/bin/test_all_modules.exe
